apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-pvc
spec:
  storageClassName: ebs-sc
  accessModes:
  - ReadWriteOnce
  resources:
     requests:
       storage: 4Gi
  selector:
      app: myvertexapp
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer